remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: TensorTract
#description: Self-Supervised Solution to the Control Problem of Articulatory Synthesis
show_downloads: True
site.github.zip_url: #ACOUSTIC_TO_ARTICULATORY_INVERSION